import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import { getPage, getPages } from '../../../sanity/sanity-utils'

const inter = Inter({ subsets: ['latin'] })


// Somehow the API is fetching after every change in Sanity.io
// export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'My personal webpage',
  description: 'Generated by create next app + sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  //get all of our pages
  const pages = await getPages();

  return (
    <html lang="en" className={inter.className}>
      <body className='max-w-5xl mx-auto py-5 sm: p-2'>

        <header className='flex items-center justify-between'>
          <Link  
          href="/"
          className='bg-gradient-to-r from-orange-400 via-red-500 to-blue-600 bg-clip-text text-transparent text-lg font-bold'  
          >
            David
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='hover:underline'> 
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className='py-10'>{children}</main>
      </body>
    </html>
  )
}
